  
language: go

go:
  - 1.13.x

before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo psql --version

install:
  - go get -v ./...
  - go build ./...
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

test:
  adapter: sqlite3
  database: ":travis_ci_test:"
  timeout: 500

stages:
  - test
services:
  - postgresql

jobs:
  include:
    - stage: test
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress
      after_success:
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
        - bash <(curl -s https://codecov.io/bash)
