  
language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

install:
  - go get -v ./...
  - go build ./...
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

stages:
  - test

jobs:
  include:
    - stage: test
      script:
        - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress